---
output:
  word_document: default
  pdf_document:
    keep_tex: true
geometry: margin=1.0in
font-size: 11pt
header-includes:
  - \usepackage{helvet}
  - \renewcommand*\familydefault{\sfdefault}
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage[left]{lineno}
  - \linenumbers
  - \raggedright
editor_options:
  chunk_output_type: console
bibliography: references.bib
csl: asm.csl
---

```{r, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(here))

opts_chunk$set(echo = FALSE)

inline_hook <- function(x){

	if(is.numeric(x)){
		if(abs(x - round(x)) < .Machine$double.eps){
			# treat as integer
			formatted <- format(x, digits=0, big.mark = ",")

		} else {
			# treat as floating point number
			formatted <- format(x, digits=2, nsmall=2, big.mark = ",")
		}
	} else {
		formatted <-x
	}

  formatted

}


knit_hooks$set(inline=inline_hook)

format_pct <- function(x, my_digits=1){

	format(x, digits=my_digits, nsmall=my_digits)

}
```

# YOUR TITLE GOES HERE - LEAVE THE # AT THE START OF THE LINE


\vspace{35mm}

Running title: INSERT RUNNING TITLE HERE

\vspace{35mm}


Your Name Here^1, Joeseph P. Schmo^2, Sally J. Rivers^1, Patrick D. Schloss^1$\dagger$^

\vspace{40mm}

$\dagger$ To whom correspondence should be addressed: pschloss@umich.edu

1\. Department of Microbiology and Immunology, University of Michigan, Ann Arbor, MI 48109

2\. Other department contact information


\newpage
\linenumbers


## Abstract


\newpage

## Introduction


## Results and Discussion


## Conclusions


## Materials and Methods


\newpage

Insert figure legends with the first sentence in bold, for example:

**Figure 1. Number of OTUs sampled among bacterial and archaeal 16S rRNA gene sequences for different OTU definitions and level of sequencing effort.** Rarefaction curves for different OTU definitions of Bacteria (A) and Archaea (B). Rarefaction curves for the coarse environments in Table 1 for Bacteria (C) and Archaea (D).


\newpage

## References
